create table GLOBAL_pessoa (id integer not null auto_increment, atendimento_preferencial bit not null, content_type varchar(255), cpf varchar(255) not null, data_criacao datetime not null, data_nascimento date, email varchar(255) not null, estado_civil varchar(255) not null, fone_celular varchar(255) not null, fone_residencial varchar(255), foto varchar(255), idoso bit not null, nacionalidade varchar(255), naturalidade varchar(255), nome varchar(255) not null, observacao longtext, portador_deficiencia bit not null, profissao varchar(255), pseudonimo varchar(255) not null, rg varchar(255), sexo varchar(255) not null, id_endereco integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_acao (id integer not null auto_increment, data_criacao datetime not null, nome varchar(100) not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_acao_processo (id integer not null auto_increment, data_criacao datetime not null, id_acao integer not null, id_processo integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_agenda (id integer not null auto_increment, assistido varchar(255) not null, color varchar(255) not null, data_fim datetime not null, data_inicio datetime not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_aluno (id integer not null auto_increment, data_criacao datetime not null, matricula varchar(20) not null, id_cabine integer not null, id_equipe integer not null, id_expediente integer not null, id_pessoa integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_aluno_processo (id integer not null auto_increment, data_criacao datetime not null, id_aluno integer not null, id_processo integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_assistido (id integer not null auto_increment, data_criacao datetime not null, id_pessoa integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_assistido_processo (id integer not null auto_increment, data_criacao datetime not null, tipo_parte varchar(50) not null, id_assistido integer not null, id_processo integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_cabine (id integer not null auto_increment, data_criacao datetime not null, nome varchar(255) not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_carga (id integer not null auto_increment, data_criacao datetime not null, data_entrega datetime, data_saida datetime not null, descricao varchar(255) not null, id_pessoa integer not null, id_processo integer not null, id_usuario integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_cidade (id integer not null auto_increment, nome varchar(255) not null, id_estado integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_disciplina (id integer not null auto_increment, data_criacao datetime not null, nome varchar(255) not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_documento (id integer not null auto_increment, content_type varchar(100) not null, data_criacao datetime not null, descricao varchar(255) not null, nome varchar(255) not null, principal bit not null, tamanho bigint not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_documento_processo (id integer not null auto_increment, data_criacao datetime not null, id_documento integer not null, id_processo integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_endereco (id integer not null auto_increment, bairro varchar(255), cep varchar(255) not null, logradouro varchar(255) not null, id_cidade integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_equipe (id integer not null auto_increment, data_criacao datetime not null, nome varchar(255) not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_estado (id integer not null auto_increment, nome varchar(255) not null, sigla varchar(255) not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_expediente (id integer not null auto_increment, ativo bit not null, data_criacao datetime not null, periodo_letivo varchar(20) not null, id_disciplina integer not null, id_funcionario integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_expediente_turma (id_expediente integer not null, id_turma integer not null) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_funcionario (id integer not null auto_increment, data_criacao datetime not null, funcao varchar(255) not null, id_pessoa integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_funcionario_processo (id integer not null auto_increment, data_criacao datetime not null, tipo_participacao varchar(100) not null, id_funcionario integer not null, id_processo integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_grupo (id integer not null auto_increment, nome varchar(255) not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_grupo_permissao (id_permissao integer not null, id_grupo integer not null, primary key (id_grupo, id_permissao)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_horario (id integer not null auto_increment, data datetime not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_mensagem (id integer not null auto_increment, conteudo varchar(255) not null, data_fim date not null, data_inicio date not null, titulo varchar(50) not null, id_usuario_ativo integer not null, id_usuario_passivo integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_permissao (id integer not null auto_increment, nome varchar(255) not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_processo (id integer not null auto_increment, data_criacao datetime not null, do_direito varchar(255), do_fato varchar(255), do_pedido varchar(255), documentos_que_faltam varchar(255), esta_com_aluno bit, extinto bit, localizacao varchar(255), primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_reu (id integer not null auto_increment, data_criacao datetime not null, id_pessoa integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_turma (id integer not null auto_increment, nome varchar(255) not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_turma_horario (id_turma integer not null, id_horario integer not null) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_usuario (id integer not null auto_increment, ativo bit not null, data_criacao datetime not null, login varchar(255) not null, senha varchar(255) not null, id_pessoa integer not null, primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table NPJ_REAL_usuario_grupo (id_usuario integer not null, id_grupo integer not null) ENGINE=InnoDB DEFAULT CHARSET=utf8;

alter table GLOBAL_pessoa add constraint fk_pessoa_endereco foreign key (id_endereco) references NPJ_REAL_endereco (id);
alter table NPJ_REAL_acao_processo add constraint fk_acao_processo_acao foreign key (id_acao) references NPJ_REAL_acao (id);
alter table NPJ_REAL_acao_processo add constraint fk_acao_processo_processo foreign key (id_processo) references NPJ_REAL_processo (id);
alter table NPJ_REAL_aluno add constraint fk_aluno_cabine foreign key (id_cabine) references NPJ_REAL_cabine (id);
alter table NPJ_REAL_aluno add constraint fk_aluno_equipe foreign key (id_equipe) references NPJ_REAL_equipe (id);
alter table NPJ_REAL_aluno add constraint fk_aluno_expediente foreign key (id_expediente) references NPJ_REAL_expediente (id);
alter table NPJ_REAL_aluno add constraint fk_aluno_pessoa foreign key (id_pessoa) references GLOBAL_pessoa (id);
alter table NPJ_REAL_aluno_processo add constraint fk_aluno_processo_aluno foreign key (id_aluno) references NPJ_REAL_aluno (id);
alter table NPJ_REAL_aluno_processo add constraint fk_aluno_processo_processo foreign key (id_processo) references NPJ_REAL_processo (id);
alter table NPJ_REAL_assistido add constraint fk_assistido_pessoa foreign key (id_pessoa) references GLOBAL_pessoa (id);
alter table NPJ_REAL_assistido_processo add constraint fk_assistido_processo_assistido foreign key (id_assistido) references NPJ_REAL_assistido (id);
alter table NPJ_REAL_assistido_processo add constraint fk_assistido_processo_processo foreign key (id_processo) references NPJ_REAL_processo (id);
alter table NPJ_REAL_carga add constraint fk_carga_pessoa foreign key (id_pessoa) references GLOBAL_pessoa (id);
alter table NPJ_REAL_carga add constraint fk_carga_processo foreign key (id_processo) references NPJ_REAL_processo (id);
alter table NPJ_REAL_carga add constraint fk_carga_usuario foreign key (id_usuario) references NPJ_REAL_usuario (id);
alter table NPJ_REAL_cidade add constraint fk_cidade_estado foreign key (id_estado) references NPJ_REAL_estado (id);
alter table NPJ_REAL_documento_processo add constraint fk_documento_processo_documento foreign key (id_documento) references NPJ_REAL_documento (id);
alter table NPJ_REAL_documento_processo add constraint fk_documento_processo_processo foreign key (id_processo) references NPJ_REAL_processo (id);
alter table NPJ_REAL_endereco add constraint fk_endereco_cidade foreign key (id_cidade) references NPJ_REAL_cidade (id);
alter table NPJ_REAL_expediente add constraint fk_expediente_disciplina foreign key (id_disciplina) references NPJ_REAL_disciplina (id);
alter table NPJ_REAL_expediente add constraint fk_expediente_funcionario foreign key (id_funcionario) references NPJ_REAL_funcionario (id);
alter table NPJ_REAL_expediente_turma add constraint fk_expediente_turma_turma foreign key (id_turma) references NPJ_REAL_turma (id);
alter table NPJ_REAL_expediente_turma add constraint fk_expediente_turma_expediente foreign key (id_expediente) references NPJ_REAL_expediente (id);
alter table NPJ_REAL_funcionario add constraint fk_funcionario_pessoa foreign key (id_pessoa) references GLOBAL_pessoa (id);
alter table NPJ_REAL_funcionario_processo add constraint fk_funcionario_processo_funcionario foreign key (id_funcionario) references NPJ_REAL_funcionario (id);
alter table NPJ_REAL_funcionario_processo add constraint fk_funcionario_processo_processo foreign key (id_processo) references NPJ_REAL_processo (id);
alter table NPJ_REAL_grupo_permissao add constraint fk_grupo_permissao_permissao foreign key (id_permissao) references NPJ_REAL_permissao (id);
alter table NPJ_REAL_grupo_permissao add constraint fk_grupo_permissao_grupo foreign key (id_grupo) references NPJ_REAL_grupo (id);
alter table NPJ_REAL_mensagem add constraint fk_mensagem_usuario_ativo foreign key (id_usuario_ativo) references NPJ_REAL_usuario (id);
alter table NPJ_REAL_mensagem add constraint fk_mensagem_usuario_passivo foreign key (id_usuario_passivo) references NPJ_REAL_usuario (id);
alter table NPJ_REAL_reu add constraint fk_reu_pessoa foreign key (id_pessoa) references GLOBAL_pessoa (id);
alter table NPJ_REAL_turma_horario add constraint fk_turma_horario_horario foreign key (id_horario) references NPJ_REAL_horario (id);
alter table NPJ_REAL_turma_horario add constraint fk_turma_horario_turma foreign key (id_turma) references NPJ_REAL_turma (id);
alter table NPJ_REAL_usuario add constraint fk_usuario_pessoa foreign key (id_pessoa) references GLOBAL_pessoa (id);
alter table NPJ_REAL_usuario_grupo add constraint fk_usuario_grupo_grupo foreign key (id_grupo) references NPJ_REAL_grupo (id);
alter table NPJ_REAL_usuario_grupo add constraint fk_usuario_grupo_usuario foreign key (id_usuario) references NPJ_REAL_usuario (id);